#!/bin/sh
#
# efergy        Starts efergy.
#

# Make sure the rtl_fm progam exists
[ -f /usr/bin/rtl_fm ] || exit 0

efergy() {
	/usr/bin/rtl_fm -f 433.68e6 -s 200000 -r 96000 -A fast 2>/dev/null | /usr/bin/EfergyRPI_log log
}

start() {
	printf "Starting efergy "
	efergy&
	echo "OK"
}
stop() {
	printf "Stopping efergy: "
	killall rtl_fm
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

