#!/bin/sh
#
# crontab        Start crontab.
#
	
start () {
	mkdir -p /var/spool/cron/
	ln -s  /etc/crontab.d /var/spool/cron/crontabs
        crond -c /etc/crontab.d
}

stop() {
        killall crond
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
